const paintingConfigs = {
  width: 580,
  height: 1040,
  clear: true,
  views: [
    {
      type: 'image',
      width: 580,
      height: 751,
      top: 15,
      left: 0,
      url: 'https://qiniu.runworld.com.cn/wxapp/images/pic_home_107@3x.png',
    },
    {
      type: 'rect',
      width: 580,
      height: 289,
      left: 0,
      top: 751,
      background: '#fff',
    },
    {
      type: 'image',
      width: 127,
      height: 42,
      left: 30,
      top: 960,
      url: 'https://qiniu.runworld.com.cn/assets/images/logo／1.png',
    },
    {
      type: 'text',
      left: 60,
      top: 850,
      content: '2019.6.30~2019.7.5',
      fontSize: 24,
      color: '#666666',
    },
    {
      type: 'text',
      width: 520,
      left: 30,
      right: 30,
      top: 775,
      lineHeight: 40,
      MaxLineNumber: 2,
      content: '搞事 | 职场荣耀争霸赛火热报名ING火热报名ING',
      breakWord: true,
      fontSize: 28,
      bolder: true,
      color: '#333333',
    },
    {
      type: 'text',
      left: 60,
      top: 890,
      lineHeight: 40,
      width: 250,
      MaxLineNumber: 2,
      breakWord: true,
      content: '12',
      fontSize: 24,
      color: '#666666',
    },
    {
      type: 'image',
      width: 18,
      height: 19,
      left: 30,
      top: 850,
      url: 'https://qiniu.runworld.com.cn/assets/images/icon／sj／1.png',
    },
    {
      type: 'image',
      width: 18,
      height: 25,
      left: 30,
      top: 890,
      url: 'https://qiniu.runworld.com.cn/assets/images/icon／dw／1.png',
    },
    {
      type: 'image',
      width: 160,
      height: 180,
      left: 400,
      top: 840,
      url: 'https://qiniu.runworld.com.cn/wxapp/images/1565348887(1).png',
    },
  ],
}

export default paintingConfigs
